version: "3.1"

services:
  frontend:
    tty: true
    environment:
      BACKEND_HOST: backend
    build: ./FrontendISE
    container_name: ise-frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
      - /front/node_modules
  postgres:
      image: "postgres:12"
      container_name: ise-database
      ports:
        - 5432:5432
      volumes:
        - my_dbdata:/var/lib/postgresql/data
      links:
        - "frontend"
      environment:
        POSTGRES_PASSWORD: root
      expose:
        - 5432
volumes:
  my_dbdata:
